def nb_cells(n):
    s=0
    for i in range(n+1, 2*n+1):
        s += 2*i
    s += 2*n+1
    return s

COEF = 0.3
GRID_RAY = 2
NB_CELLS = nb_cells(GRID_RAY)
NB_PLAYERS = 1

APP_PIXDIM = (2800 * COEF, 2300 * COEF)
MESSAGE_PIXDIM = (APP_PIXDIM[0], 200 * COEF)

IMGCELL_PIXDIM = (456*COEF, 342*COEF)
IMGPLAYER_PIXDIM = (590 * COEF * 0.8, 632 * COEF * 0.8)
PIXSIZE_STAGE_CELL = [0, 80 * COEF]
PIXSIZE_SHADOW_PLAYER = [90 * COEF, 0]

PIXSIZE_VECTOR_PLAYER_CELL = [IMGCELL_PIXDIM[0]/2 - IMGPLAYER_PIXDIM[0]/2 - PIXSIZE_SHADOW_PLAYER[0]/2, IMGCELL_PIXDIM[1]/2 - IMGPLAYER_PIXDIM[1]]
POS_CENTER = [(APP_PIXDIM[0] - IMGCELL_PIXDIM[0])/2, MESSAGE_PIXDIM[1] + (APP_PIXDIM[1] - IMGCELL_PIXDIM[1])/2]

MV_R = [450 * COEF, 0]
MV_DR = [228 * COEF, 190 * COEF]
